# Generated by Django 5.0.1 on 2024-02-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cuscart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuscart',
            old_name='user',
            new_name='username',
        ),
    ]
