# Generated by Django 5.0.1 on 2024-02-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_cuscart_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CusCart',
            new_name='CustCart',
        ),
    ]
