# Generated by Django 5.0.1 on 2024-02-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_cuscart_custcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custcart',
            old_name='order_id',
            new_name='cart_id',
        ),
    ]
