# Generated by Django 5.0.1 on 2024-02-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_order_id_custcart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default=(('rest', 'rest'), ('cust', 'cust'), ('admin', 'admin')), max_length=50),
        ),
    ]
