# Generated by Django 5.0.1 on 2024-02-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('cust', 'cust'), ('rest', 'rest')], max_length=50),
        ),
    ]
