# Generated by Django 5.0.1 on 2024-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustRatingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.IntegerField(default=1)),
                ('ratings', models.FloatField()),
                ('feedback', models.CharField(max_length=200)),
                ('username', models.CharField(default='username', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('cust', 'cust'), ('admin', 'admin'), ('rest', 'rest')], max_length=50),
        ),
    ]
