# Generated by Django 5.0.3 on 2024-03-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_custratingfeedback_alter_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('prod_code', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('user', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('rest', 'rest'), ('cust', 'cust'), ('admin', 'admin')], max_length=50),
        ),
    ]
