# Generated by Django 5.0.1 on 2024-02-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_added_by_item_prod_code_item_rest_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('prod_code', models.IntegerField(default=100)),
                ('item_name', models.CharField(max_length=200)),
                ('operation', models.CharField(max_length=100)),
            ],
        ),
    ]
